import longoNarration from "./narration/longo.json";
import curtoNarration from "./narration/curto.json";
import type { Clip, Cue, Version } from "./timeline";

// The two cuts of the video. Both tell the same story with the same scenes;
// they differ in the script (narration/<id>.json), in the pace, and so in the
// words each animation fires on.

const w = (clip: string, word: string, offset = 0, nth = 0): Cue => ({ clip, word, offset, nth });
const start = (clip: string, offset = 0): Cue => ({ clip, at: "start", offset });
const end = (clip: string, offset = 0): Cue => ({ clip, at: "end", offset });

/** The first cut, 2:34, at the voice's own pace. */
export const longo: Version = {
  id: "longo",
  narration: longoNarration as Clip[],
  lead: { ecosystem: 1.2, brand: 0.5, download: 0.5, qr: 0.6, choose: 0.5, features: 0.5, warning: 0.6, cta: 0.5 },
  tail: { ecosystem: 0.7, brand: 1.0, download: 1.5, qr: 0.8, choose: 1.2, features: 1.2, warning: 1.0, cta: 3.5 },
  pauses: { "02": 0.3, "03": 0.6, "04": 1.4, "08": 1.8, "10": 0.6, "11": 0, "12": 0.5, "13": 0.5, "15": 0.5, "16": 0.6, "17": 0.6, "19": 0.4 },
  pause: 0.4,
  enter: 16,
  out: 12,
  cues: {
    "tools.gather": w("01", "conecta", -6),
    "tools.gmail": w("02", "Gmail"),
    "tools.agenda": w("02", "agenda"),
    "tools.drive": w("02", "Drive"),
    "tools.slack": w("02", "Slack"),
    "tools.notion": w("02", "Notion"),
    "tools.jira": w("02", "Jira"),
    "tools.github": w("02", "GitHub"),
    "tools.all": w("02", "Tudo"),
    "tools.dim": start("03"),
    "tools.alone": w("03", "fora", -4),
    "tools.named": w("03", "WhatsApp"),
    "tools.solved": w("04", "resolvido", -2),
    "brand.tag1": w("05", "seu", -4),
    "brand.tag2": w("05", "direto", -4),
    "download.mac": w("06", "Mac", -3),
    "download.windows": w("06", "Windows", -3),
    "download.linux": w("06", "Linux", -3),
    "download.click": w("06", "Linux", 8),
    "download.end": end("06"),
    "qr.qr": w("07", "QR"),
    "qr.phone": w("07", "celular", -6),
    "qr.devices": w("07", "Dispositivos"),
    "qr.aim": w("07", "aponte"),
    "qr.ok": start("08", -10),
    "choose.scroll": start("09", 6),
    "choose.pick": w("09", "passo", 0, 1),
    "choose.add": w("10", "clique"),
    "choose.side": w("10", "Codex", -10),
    "choose.codex": w("10", "Codex", -4),
    "choose.cursor": w("10", "Cursor", -4),
    "choose.others": w("10", "outras", -4),
    "choose.paste": w("10", "texto", -4),
    "choose.copied": w("10", "colar"),
    "features.ask1": start("11", 20),
    "features.read": w("12", "ler"),
    "features.sum": w("12", "resumir", -14),
    "features.ask2": start("13", -2),
    "features.sent": w("13", "envia"),
    "features.f0": w("12", "conversas", -3),
    "features.f1": w("12", "achar", -3),
    "features.f2": w("12", "resumir", -3),
    "features.f3": w("13", "responde", -3),
    "features.f4": w("13", "fotos", -3),
    "features.f5": w("13", "transcreve", -3),
    "features.f6": w("13", "enquetes", -3),
    "warning.sign": start("14", -6),
    "warning.head": start("15"),
    "warning.rules": w("15", "regras", -4),
    "warning.block": w("15", "bloquear", -4),
    "warning.list": start("16"),
    "warning.auto": w("16", "respostas", -4),
    "warning.same": w("16", "mesma", -4),
    "warning.purpose": w("16", "levar", -4),
    "warning.risk": start("17"),
    "warning.normal": w("17", "normal", -4),
    "cta.free": w("18", "gratuito", -4),
    "cta.open": w("18", "codigo", -4),
    "cta.github": w("18", "GitHub", -4),
    "cta.download": w("19", "Baixe", -4),
    "cta.link": w("19", "link"),
    "cta.mac": w("19", "Mac", -4),
    "cta.windows": w("19", "Windows", -4),
    "cta.linux": w("19", "Linux", -4),
  },
};

/** The one-minute cut: a tighter script, the voice sped up, shorter scenes. */
export const curto: Version = {
  id: "curto",
  narration: curtoNarration as Clip[],
  lead: { ecosystem: 0.4, brand: 0.15, download: 0.15, qr: 0.15, choose: 0.15, features: 0.2, warning: 0.2, cta: 0.15 },
  tail: { ecosystem: 0.7, brand: 0.5, download: 0.8, qr: 1.0, choose: 0.5, features: 0.4, warning: 0.4, cta: 1.8 },
  pauses: { "03": 0.4, "10": 0.2, "11": 0.25 },
  pause: 0.15,
  enter: 10,
  out: 8,
  cues: {
    "tools.gather": w("01", "conecta", -6),
    "tools.gmail": w("01", "Gmail"),
    "tools.agenda": w("01", "agenda"),
    "tools.drive": w("01", "Drive"),
    "tools.slack": w("01", "Slack"),
    "tools.jira": w("01", "Jira"),
    "tools.github": w("01", "GitHub"),
    "tools.all": w("01", "GitHub", 10),
    "tools.dim": start("02"),
    "tools.alone": w("02", "WhatsApp", -6),
    "tools.named": w("02", "fora"),
    "tools.solved": w("03", "resolvido", -2),
    "brand.tag1": w("04", "MCP", 4),
    "brand.tag2": w("04", "MCP", 10),
    "download.mac": w("05", "Mac", -3),
    "download.windows": w("05", "Windows", -3),
    "download.linux": w("05", "Linux", -3),
    "download.click": w("05", "Linux", 6),
    "download.end": end("05"),
    "qr.qr": w("06", "QR", -2),
    "qr.phone": w("06", "WhatsApp", -6),
    "qr.devices": w("06", "Dispositivos", -2),
    "qr.aim": w("06", "conectados"),
    "qr.ok": end("06", 14),
    "choose.scroll": start("07", -6),
    "choose.pick": w("07", "IA"),
    "choose.add": w("07", "clique"),
    "choose.side": w("07", "Codex", -10),
    "choose.codex": w("07", "Codex", -4),
    "choose.cursor": w("07", "Cursor", -4),
    "choose.others": w("07", "outras", -4),
    "choose.paste": w("07", "texto", -4),
    "choose.copied": w("07", "colar"),
    "features.ask1": start("08", 10),
    "features.read": w("08", "ler"),
    "features.sum": w("08", "resumir", -8),
    "features.ask2": w("08", "responder", -2),
    "features.sent": w("08", "mandar"),
    "features.f0": w("08", "conversas", -3),
    "features.f1": w("08", "achar", -3),
    "features.f2": w("08", "resumir", -3),
    "features.f3": w("08", "responder", -3),
    "features.f4": w("08", "fotos", -3),
    "features.f5": w("08", "transcrever", -3),
    "features.f6": w("08", "enquetes", -3),
    "warning.sign": start("09", -6),
    "warning.head": w("09", "ele", -4),
    "warning.rules": w("09", "regras", -4),
    "warning.block": w("09", "bloquear", -4),
    "warning.list": start("10"),
    "warning.auto": w("10", "respostas", -4),
    "warning.same": w("10", "mesma", -4),
    "warning.risk": start("11"),
    "warning.normal": w("11", "ritmo", -4),
    "cta.free": w("12", "gratuito", -4),
    "cta.open": w("12", "codigo", -4),
    "cta.github": w("12", "GitHub", -4),
    "cta.download": w("12", "Baixe", -4),
    "cta.link": w("12", "link"),
  },
};

export const VERSIONS = [longo, curto];
